In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
import re
import plotly.graph_objects as go
import plotly.express as px
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_absolute_percentage_error
import plotly.graph_objects as go

# **ТИП ТОПЛИВА И ОБЬЕМ ДВИГАТЕЛЯ. ЛИНЕЙНАЯ МОДЕЛЬ**

In [2]:
processed_df = pd.read_csv('processed_df.csv')

In [3]:
processed_df.columns

Index(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan',
       'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'year', 'selling_price',
       'km_driven', 'Diesel', 'Individual', 'Dealer', 'Manual', 'First Owner',
       'Second Owner', 'Third Owner', 'Fourth & Above Owner', 'milage',
       'engine', 'max_power', 'torque', 'RPM_min', 'seats'],
      dtype='object')

**ВЫБОР ДВУХ ПРИЗНАКОВ- ТИП ТОПЛИВА И ОБЬЕМ ДВИГАТЕЛЯ**

In [4]:
processed_df = processed_df.loc[:, ['Diesel', 'engine', 'selling_price']].dropna()

**НОРМАЛИЗУЕМ ПРИЗНАКИ ПО СРЕДСТВАМ SNADART SCALLER**

In [5]:
scaler = StandardScaler()
x = scaler.fit_transform(processed_df.loc[:, ['Diesel', 'engine']])
y = processed_df['selling_price']

**ДЛЯ НАЧАЛА ПОПРОБУЕМ ОБУЧИТЬ НА ПРИМЕРЕ ОДНОЙ СТЕПЕНИ ПОЛИНОМА**

In [6]:
poly = PolynomialFeatures(2)
x_poly = poly.fit_transform(x)
x_poly

array([[ 1.        ,  0.90175469, -0.42334643,  0.81316153, -0.38175463,
         0.1792222 ],
       [ 1.        ,  0.90175469,  0.07346712,  0.81316153,  0.06624932,
         0.00539742],
       [ 1.        , -1.10894904,  0.07147987,  1.22976797, -0.07926753,
         0.00510937],
       ...,
       [ 1.        ,  0.90175469, -0.42334643,  0.81316153, -0.38175463,
         0.1792222 ],
       [ 1.        ,  0.90175469, -0.12923281,  0.81316153, -0.11653629,
         0.01670112],
       [ 1.        ,  0.90175469, -0.12923281,  0.81316153, -0.11653629,
         0.01670112]])

In [25]:
x

array([[ 0.90175469, -0.42334643],
       [ 0.90175469,  0.07346712],
       [-1.10894904,  0.07147987],
       ...,
       [ 0.90175469, -0.42334643],
       [ 0.90175469, -0.12923281],
       [ 0.90175469, -0.12923281]])

In [7]:
reg_1 = LinearRegression(fit_intercept=False)
cv_results = cross_validate(reg_1, x_poly, y, cv=5, return_train_score=True, scoring='neg_mean_absolute_percentage_error')
print(cv_results['test_score'])
print(cv_results['train_score'])

[-0.91299339 -0.9289455  -0.86285544 -0.96217484 -0.93307167]
[-0.91021517 -0.93930558 -0.89954876 -0.9289453  -0.91526563]


**ЗАВИСИМОСТЬ СТЕПЕНИ ПОЛИНОМА ОТ ПОТЕРЬ**

**1. СОЗДАДИМ СПИСОК СТЕПЕНЕЙ ПОЛИНОМА**

In [12]:
poly_power = np.arange(1, 30, 1)
poly_power

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**СОЗДАДИМ ДФ В КОТОРЫЙ БУДЕМ ЗАПИСЫВАТЬ РЕЗУЛЬТАТЫ**

**ЦИКЛ С ПЕРЕБОРОМ СТЕПЕНЕЙ ПОЛИНОМА. ПОТЕРИ- MAE**

In [13]:
poly_loss_df = pd.DataFrame({'poly': [], 'loss_train': [], 'loss_test': []})
for p in poly_power:
    # генерация признаков с полиномом степени p
    polynom = PolynomialFeatures(p)
    x_poly = polynom.fit_transform(x)
    # оздание обьекта линейной модели обучения. fit_intercept=False для того, что бы модель не добавляла единичный столбец к матрице признаков для свободного коэффициента w
    reg = LinearRegression(fit_intercept=False)
    # применяем кросс-валидацию для поиска потерь
    cv_results = cross_validate(reg_1, x_poly, y, cv=5, return_train_score=True, scoring='neg_mean_absolute_error')
    # записываем стредние потери для тестовых и тренировочных датасетов в датафрейм
    poly_loss_df.loc[len(poly_loss_df.index)] = [p, np.mean(np.array(cv_results['train_score'])), np.mean(np.array(cv_results['test_score']))]
poly_loss_df

poly    loss_train     loss_test
0    1.0 -3.736486e+05 -3.738408e+05
1    2.0 -3.767629e+05 -3.771661e+05
2    3.0 -3.731772e+05 -3.736786e+05
3    4.0 -3.861924e+05 -3.868821e+05
4    5.0 -3.588100e+05 -3.604825e+05
5    6.0 -3.556181e+05 -3.578117e+05
6    7.0 -3.356167e+05 -3.380178e+05
7    8.0 -3.387027e+05 -3.430534e+05
8    9.0 -3.186971e+05 -3.208235e+05
9   10.0 -3.159653e+05 -3.389272e+05
10  11.0 -3.099876e+05 -3.906987e+05
11  12.0 -3.099028e+05 -4.806240e+05
12  13.0 -3.089391e+05 -1.116729e+06
13  14.0 -3.069554e+05 -4.888335e+06
14  15.0 -3.009312e+05 -2.076527e+06
15  16.0 -2.821774e+05 -1.238369e+08
16  17.0 -2.786926e+05 -4.499218e+08
17  18.0 -2.639498e+05 -3.819926e+08
18  19.0 -2.588910e+05 -1.667921e+09
19  20.0 -2.649748e+05 -3.210581e+10
20  21.0 -3.090735e+05 -6.978864e+10
21  22.0 -3.701228e+05 -9.148554e+10
22  23.0 -4.223812e+05 -2.000780e+11
23  24.0 -3.286273e+05 -1.898739e+11
24  25.0 -4.268367e+05 -1.466659e+11
25  26.0 -6.439455e+05 -9.284050e+09
26  27.0 -8.828334e+05 -4.314185e+11
27  28.0 -2.165674e+06 -7.354344e+11
28  29.0 -5.600479e+05 -3.257474e+11

In [26]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=poly_loss_df['poly'], y=poly_loss_df['loss_train'], mode='lines', name='train_score'))
fig.add_trace(go.Scatter(x=poly_loss_df['poly'], y=poly_loss_df['loss_test'], mode='lines', name='test_score'))
fig.update_layout(width = 1400, height=1000, yaxis_range=[-400000, -300000])
fig.write_html('ENGINE_VOL_DIESEL____loss_mae_test_VS_loss_mae_train.html')

**ПОТЕРИ MAPE**

In [22]:
poly_loss_df_mape = pd.DataFrame({'poly': [], 'loss_train': [], 'loss_test': []})
for p in poly_power:
    # генерация признаков с полиномом степени p
    polynom = PolynomialFeatures(p)
    x_poly = polynom.fit_transform(x)
    # оздание обьекта линейной модели обучения. fit_intercept=False для того, что бы модель не добавляла единичный столбец к матрице признаков для свободного коэффициента w
    reg = LinearRegression(fit_intercept=False)
    # применяем кросс-валидацию для поиска потерь
    cv_results = cross_validate(reg_1, x_poly, y, cv=5, return_train_score=True, scoring='neg_mean_absolute_percentage_error')
    # записываем стредние потери для тестовых и тренировочных датасетов в датафрейм
    poly_loss_df_mape.loc[len(poly_loss_df_mape.index)] = [p, np.mean(np.array(cv_results['train_score'])), np.mean(np.array(cv_results['test_score']))]
poly_loss_df_mape

poly  loss_train      loss_test
0    1.0   -0.880270      -0.880490
1    2.0   -0.918656      -0.920008
2    3.0   -0.888607      -0.889161
3    4.0   -0.978393      -0.980370
4    5.0   -0.896167      -0.898502
5    6.0   -0.893544      -0.897627
6    7.0   -0.806662      -0.811735
7    8.0   -0.828495      -0.835215
8    9.0   -0.774560      -0.779498
9   10.0   -0.768946      -0.794867
10  11.0   -0.770207      -0.851777
11  12.0   -0.764190      -0.937837
12  13.0   -0.769811      -1.578810
13  14.0   -0.773975      -5.358389
14  15.0   -0.750147      -2.528934
15  16.0   -0.698657    -124.257580
16  17.0   -0.697337    -450.340871
17  18.0   -0.668209    -382.401482
18  19.0   -0.656145   -1668.323200
19  20.0   -0.671594  -32106.231642
20  21.0   -0.816243  -69789.170038
21  22.0   -0.925218  -91486.113139
22  23.0   -1.091378 -200078.733563
23  24.0   -0.882661 -189874.494774
24  25.0   -1.164031 -146666.607122
25  26.0   -1.847447   -9285.250789
26  27.0   -2.916038 -431420.506554
27  28.0   -8.186374 -735440.504656
28  29.0   -1.308041 -325748.111506

In [27]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=poly_loss_df_mape['poly'], y=poly_loss_df_mape['loss_train'], mode='lines', name='train_score'))
fig.add_trace(go.Scatter(x=poly_loss_df_mape['poly'], y=poly_loss_df_mape['loss_test'], mode='lines', name='test_score'))
fig.update_layout(width = 1200, height=1000, yaxis_range=[-1, -0.6])
fig.write_html('ENGINE_VOL_DIESEL____loss_mape_test_VS_loss_mape_train.html')

**НА ОБОИХ ГРАФИКАХ ВИДНО, ЧТО НАИЛУЧШАЯ СТЕПЕНЬ ПОЛИНОМА ЯВЛЯЕТСЯ 9**

# **ПРОБЕГ И КРУТЯЩИЙ МОМЕНТ. ЛИНЕЙНАЯ МОДЕЛЬ**

In [ ]:
processed_df = pd.read_csv('processed_df.csv')
kmdriven_torque_data = processed_df.loc[:, ['km_driven', 'torque']]